### ISSUE TITLE
question

### ISSUE THREAD

**Issue by OzzyHelix** [AkBKukU/MinecraftServerSuite#1]
is this a minecraft server panel because I have a centos vps running on lemp stack and was wondering how to use this

**Comment by AkBKukU** [comment]
This is project is divided into two parts:
`minecraftd` is an upstart service for managing when and how the Minecraft server is started when the system boots
`mcmanager` is a script for doing administration tasks 

There is no panel or front-end included in this.

**Comment by OzzyHelix** [comment]
ok that makes sense looking at the code
